// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ReceiptsApp.Infrastructure.Receipts.Persistence;

#nullable disable

namespace ReceiptsApp.Infrastructure.Receipts.Persistence.Migrations
{
    [DbContext(typeof(ReceiptsDbContext))]
    partial class ReceiptsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.Market", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Country").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("Markets");
            });

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.Receipt", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("nvarchar(3)");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<Guid>("MarketId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("PurchasedAtUtc").HasColumnType("datetime2");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,2)");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("MarketId");
                b.HasIndex("UserId", "PurchasedAtUtc");
                b.ToTable("Receipts");
            });

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.ReceiptItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Name").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<int>("Quantity").HasColumnType("int");
                b.Property<Guid>("ReceiptId").HasColumnType("uniqueidentifier");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("ReceiptId");
                b.ToTable("ReceiptItems");
            });

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.Receipt", b =>
            {
                b.HasOne("ReceiptsApp.Domain.Entities.Market", "Market")
                    .WithMany("Receipts")
                    .HasForeignKey("MarketId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Market");
            });

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.ReceiptItem", b =>
            {
                b.HasOne("ReceiptsApp.Domain.Entities.Receipt", null)
                    .WithMany("Items")
                    .HasForeignKey("ReceiptId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.Market", b =>
            {
                b.Navigation("Receipts");
            });

            modelBuilder.Entity("ReceiptsApp.Domain.Entities.Receipt", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
